---
 - name: User operations
   hosts: all
   become: true
   vars:
     user: "user"
     password: "pass"
   tasks:
     - name: Change Password
       ansible.builtin.user:
         name: "{{ user }}"
         state: present
         password: "{{ password | password_hash('sha512') }}"
...
