---
 - name: Add User
   hosts: all
   become: true
   vars:
     user: "user"
     key_dir: /home/ansible/.ssh/id_rsa.pub
   tasks:
     - name: Add user to sodoers
       lineinfile:
         dest: /etc/sudoers
         line: '"{{ user }}"        ALL=(ALL)       NOPASSWD: ALL'

     - name: Set authorized key taken from file
       ansible.posix.authorized_key:
         user: "{{ user }}"
         state: present
         key: "{{ lookup('file', '{{ key_dir }}') }}"
...
