---
 - name: User operations
   hosts: tes-ubuntu
   become: true
   vars:
     user: "user"
     password: "encrypted_password"
     comment: "description_user"
   tasks:
     - name: Create user
       ansible.builtin.user:
         name: "{{ user }}"
         comment: "{{ comment }}"
         shell: /bin/bash
         home: '/home/"{{ user }}"'
         password: "{{ password }}"
...
