---

- name: Disable swap (1/2)
  shell: |
    swapoff -a

- name: Disable swap (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Install Containerd - Download (1/4)
  get_url:
    url: https://github.com/containerd/containerd/releases/download/v1.7.0/containerd-1.7.0-linux-amd64.tar.gz
    dest: /tmp/containerd.tgz

- name: Install Containerd - Discompact (2/4)
  unarchive:
    src: /tmp/containerd.tgz
    dest: /usr/local
    remote_src: yes

- name: Install Containerd - Config Startup (3/4)
  copy:
    src: ./files/containerd.service
    dest: /usr/local/lib/systemd/system/
    owner: root
    group: root
    mode: '0755'

- name: Install Containerd - Startup (4/4)
  systemd:
    name: containerd
    state: started
    enabled: true

- name: Install RunC - Download (1/2)
  get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.1.4/runc.amd64
    dest: /tmp/runc.amd64

- name: Install RunC (2/2)
  shell: |
    install -m 755 /tmp/runc.amd64 /usr/local/sbin/runc

- name: Configure Systemd in container runtime (1/3)
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'

- name: Configure Systemd in container runtime (2/3)
  shell: |
    containerd config default | sudo tee /etc/containerd/config.toml

- name: Configure Systemd in container runtime (3/3)
  replace:
    path: /etc/containerd/config.toml
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
    - { regexp: 'SystemdCgroup = false', replace: 'SystemdCgroup = true' }
    - { regexp: 'sandbox_image = "registry.k8s.io/pause:3.8', replace: 'sandbox_image = "registry.k8s.io/pause:3.2' }

- name: Restart Containerd (1/1)
  systemd:
    name: containerd
    state: restarted
...
